source 'https://rubygems.org'

gem 'guard'
gem 'guard-sass'
gem 'guard-coffeescript'
gem 'guard-copy'
gem 'guard-jammit'
gem 'guard-livereload'
gem 'terminal-notifier-guard'
gem 'siteleaf', '2.0.0.pre.beta7'
